# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ESPProvisionSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ESPProvisionSample
  pod 'ESPProvision', '2.1.0'
  pod 'MBProgressHUD'

  target 'ESPProvisionSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ESPProvisionSampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['ARCHS'] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end