# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

plugin 'cocoapods-keys', {
  :project => "EspressifProvision",
  :keys => ["UserPoolId","UserPoolAppClientId","UserPoolAppClientSecret","Staging_UserPoolId","Staging_UserPoolAppClientId","Staging_UserPoolAppClientSecret"]
}

abstract_target 'EspressifProvisionAll' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Espressif

  pod 'SwiftProtobuf', '~> 1.5.0'
  pod 'Curve25519', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'AWSCore'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSMobileClient'
  pod 'Alamofire', '~> 5.0.0'
  pod 'SideMenu'
  pod 'RangeSeekSlider'
  pod 'ReachabilitySwift'
  pod 'CollectionViewCenteredFlowLayout'
  pod 'JWTDecode', '~> 2.4'
  pod 'M13Checkbox'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'

  target 'EspressifProvision'
  target 'EspressifProvisionTests' do
  end
end
