# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

abstract_target 'EspressifProvisionAll' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Espressif

  pod 'SwiftProtobuf', '~> 1.5.0'
  pod 'Curve25519', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'BlueSocket'
  
  target 'EspressifProvision'
  target 'EspressifProvisionTests' do
  end

end
